name: local-dev
services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=accounting_admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=accounting
    ports:
      - 5432:5432
    volumes:
      - ./database-data:/var/lib/postgresql/data
