name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
    - src/**
    - entity/**
    - migration/**
    - Cargo.toml

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Rsync deployments
      uses: burnett01/rsync-deployments@5.1
      with:
        path: ./target/debug/accounting
        remote_path: /home/ubuntu/accounting
        remote_host: "${{ secrets.REMOTE_SERVER_IP }}"
        remote_user: ubuntu
        remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
    - name: Deploy to Remote Server
      uses: appleboy/ssh-action@master
      with:
        host: "${{ secrets.REMOTE_SERVER_IP }}"
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          nohup ./accounting > accounting.log 2>&1 &
